### ISSUE TITLE
Typescript typings

### ISSUE THREAD

**Issue by WorldMaker** [snabbdom-jsx/snabbdom-jsx#22]
Would you be interesting in the typing definition files to get JSX in Typescript (TSX) working? I'd be happy to PR the ones that I have been using for some time (and just updated for the latest snabbdom). (Related to #11 it appears.)

**Comment by yelouafi** [comment]
Sure thing! I'm not maintaining this project actually but PRs are welcome

**Comment by WorldMaker** [comment]
Would you wish to pass on maintainership?

**Comment by yelouafi** [comment]
sorry for the delay. Sure I'll be glad if someone could take this. Interested?

**Comment by WorldMaker** [comment]
I'm interested, yes.
